stages:
  - build
  - test
  - deploy

variables:
  VENV_PATH: ".venv"
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"

cache:
  paths:
    - .cache/pip/

build:
  stage: build
  image: python:3.13
  script:
    - python --version
    - python -m venv $VENV_PATH
    - source $VENV_PATH/bin/activate
    - pip install --upgrade pip
    - pip install -r requirements.txt
    - python -m compileall app
  artifacts:
    name: "api-productos-build-$CI_COMMIT_SHORT_SHA"
    expire_in: 1 hour
    paths:
      - app/
      - tests/
      - requirements.txt
      - .venv/
    exclude:
      - .venv/**/*.pyc
      - .venv/**/__pycache__/**

test_coverage:
  stage: test
  image: python:3.13
  needs:
    - job: build
      artifacts: true
  script:
    - source $VENV_PATH/bin/activate
    - pytest --cov=app --cov-report=term --cov-report=xml tests/
  coverage: '/TOTAL.*\s+(\d+)%/'
  artifacts:
    when: always
    expire_in: 1 week
    paths:
      - coverage.xml
    reports:
      coverage_report:
        coverage_format: cobertura
        path: coverage.xml

deploy:
  stage: deploy
  image: mcr.microsoft.com/azure-cli
  needs:
    - job: build
      artifacts: true
    - job: test_coverage
      artifacts: true
  script:
    - echo "Desplegando API en Azure..."
    - source $VENV_PATH/bin/activate
    - az login --service-principal -u $AZURE_CLIENT_ID -p $AZURE_CLIENT_SECRET --tenant $AZURE_TENANT_ID
    - az webapp up --name $AZURE_APP_NAME --resource-group $AZURE_RESOURCE_GROUP --runtime "PYTHON:3.13"
  only:
    - main